---
# Restarts latency-prototype
- hosts: all
  remote_user: ubuntu
  sudo: yes
  tasks:
    # Restart server
    - name: restart server
      action: supervisorctl name=latency-prototype state=restarted
